### ISSUE TITLE
Pipeline Rules not processing rules

### ISSUE THREAD

**Issue by ledge39** [alias454/graylog-bro-content-pack#3]
Can you help I am struggling to import Zeek logs into Graylog

I am receiving logs into Graylog
![Screenshot 2020-07-23 at 09 51 47](https://user-images.githubusercontent.com/37451439/88268473-72d14980-ccca-11ea-9461-207e5e5c296e.png)

The Stream rules are working
![Screenshot 2020-07-23 at 09 52 21](https://user-images.githubusercontent.com/37451439/88268539-8a103700-ccca-11ea-8d87-b7b14cb73d9c.png)

but the pipeline rules are not processing messages
![Screenshot 2020-07-23 at 09 51 23](https://user-images.githubusercontent.com/37451439/88268614-a1e7bb00-ccca-11ea-8a55-a6f7a2cb0a3c.png)

Any help will be appreciated

**Comment by alias454** [comment]
@ledge39 Check your Message Processors Configuration. If I remember corectly the default has to be updated. It should look like 
![Screenshot from 2020-08-01 14-11-01](https://user-images.githubusercontent.com/10768415/89108805-22ac6280-d401-11ea-8f66-53915e8c94c9.png)

The Pipeline Processor should come after the Message Filter Chain
